services:
  crew:
    build: .
    container_name: crew-app
    
    # Use the .env file from crew directory
    env_file:
      - crew/.env
    
    # Volume mounts
    volumes:
      - ./output:/app/output              # Save outputs to your computer
      - ./crew/src:/app/src:ro           # Live code reload (read-only)
      - ./crew/knowledge:/app/knowledge:ro # Knowledge base access
    
    # Only restart if manually stopped (not if crew completes)
    restart: "no"
    
    # Health check - ensure container is running
    healthcheck:
      test: ["CMD", "echo", "Container is healthy"]
      interval: 30s      # Check every 30 seconds
      timeout: 5s        # Wait 5 seconds for response
      retries: 3         # Try 3 times before marking unhealthy
      start_period: 10s  # Wait 10s before first check
    
    # Resource limits (prevents runaway processes)
    deploy:
      resources:
        limits:
          cpus: '2.0'      # Max 2 CPU cores
          memory: 2G       # Max 2GB RAM
        reservations:
          cpus: '0.5'      # Reserve 0.5 CPU cores
          memory: 512M     # Reserve 512MB RAM
    
    # Security - no privilege escalation
    security_opt:
      - no-new-privileges:true
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Max 10MB per log file
        max-file: "3"      # Keep 3 log files max
    
    # Keep container running but don't auto-run crew
    tty: true
    stdin_open: true
    
    working_dir: /app

# Container stays running, user runs crew manually! 🎮 